### ISSUE TITLE
Console Error message: Could not pass event PlayerJoinEvent

### ISSUE THREAD

**Issue by fallerOfFalls** [RichardsProjects/AutismChat3#32]
After installing build 28 this happens every time I log in:

``` yaml
[08:03:09] [User Authenticator #17/INFO]: UUID of player harpereaves is fb39bd20-6d3f-4a28-b77d-09bf3813b8b7
[08:03:09] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to AutismChat3 v9
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[minecraft_server.jar:git-Spigot-2ec6f06-7722428]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-Spigot-2ec6f06-7722428]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [minecraft_server.jar:git-Spigot-2ec6f06-7722428]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [minecraft_server.jar:git-Spigot-2ec6f06-7722428]
at net.minecraft.server.v1_8_R2.PlayerList.onPlayerJoin(PlayerList.java:296) [minecraft_server.jar:git-Spigot-2ec6f06-7722428]
at net.minecraft.server.v1_8_R2.PlayerList.a(PlayerList.java:156) [minecraft_server.jar:git-Spigot-2ec6f06-7722428]
at net.minecraft.server.v1_8_R2.LoginListener.b(LoginListener.java:144) [minecraft_server.jar:git-Spigot-2ec6f06-7722428]
at net.minecraft.server.v1_8_R2.LoginListener.c(LoginListener.java:54) [minecraft_server.jar:git-Spigot-2ec6f06-7722428]
at net.minecraft.server.v1_8_R2.NetworkManager.a(NetworkManager.java:231) [minecraft_server.jar:git-Spigot-2ec6f06-7722428]
at net.minecraft.server.v1_8_R2.ServerConnection.c(ServerConnection.java:148) [minecraft_server.jar:git-Spigot-2ec6f06-7722428]
at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:811) [minecraft_server.jar:git-Spigot-2ec6f06-7722428]
at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [minecraft_server.jar:git-Spigot-2ec6f06-7722428]
at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [minecraft_server.jar:git-Spigot-2ec6f06-7722428]
at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [minecraft_server.jar:git-Spigot-2ec6f06-7722428]
at java.lang.Thread.run(Thread.java:745) [?:1.7.0_75]
Caused by: java.lang.NullPointerException
at net.richardprojects.autismchat3.Utils.colorCodes(Utils.java:24) ~[?:?]
at net.richardprojects.autismchat3.events.LoginEvent.loginEvent(LoginEvent.java:114) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_75]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_75]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_75]
at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_75]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[minecraft_server.jar:git-Spigot-2ec6f06-7722428]
... 14 more
[08:03:09] [Server thread/INFO]: harpereaves[/87.243.219.115:15105] logged in with entity id 6431 at ([world]155.69999998807907, 75.0, 277.553415167807)
```

**Comment by fallerOfFalls** [comment]
also apparently autismchat is completely broken. nothing works at all. I'm guessing it's the same issue.

**Comment by RichardB122** [comment]
Okay I fixed it and tested it in build 29. The problem was I made a syntax error in the messages.yml file.
